mutation ($locale: String!, $path: String!) {
  pages {
    deleteFolder(locale: $locale, path: $path) {
      responseResult {
        succeeded
        message
      }
      folder {
        locale
        path
        title
      }
    }
  }
}

