query($id: Int!) {
  pages {
    single(id:$id) {
      id
      path
      hash
      title
      description
      isPrivate
      isPublished
      privateNS
      publishStartDate
      publishEndDate
      contentType
      createdAt
      updatedAt
      editor
      locale
      authorId
      authorName
      authorEmail
      creatorId
      creatorName
      creatorEmail
      approvalStatus
      approvalComment
      pendingVersionId
      approverName
      approverEmail
      tags {
        tag
      }
      pendingVersion {
        versionId
        authorId
        authorName
        versionDate
        workflowStatus
        title
        description
        publishStartDate
        publishEndDate
        isPublished
        tags
      }
    }
  }
}
